//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Holiday
    {
        public int Holiday_Id { get; set; }
        public Nullable<System.DateTime> Holiday1 { get; set; }
        public string Holiday_Name { get; set; }
    }
}
